const ERROR = {
  NOT_A_NUMBER: 'NOT_A_NUMBER',
  IS_EMPTY: 'IS_EMPTY',
  NOT_AN_ARRAY: 'NOT_AN_ARRAY',
  NOT_AN_OBJECT: 'NOT_AN_OBJECT',
  REQUIRED_BUT_EMPTY: 'REQUIRED_BUT_EMPTY',
  NOT_A_BOOLEAN: 'NOT_A_BOOLEAN',
  NOT_PARAM_TYPE: 'NOT_PARAM_TYPE',
}

export default ERROR
